### ISSUE TITLE
Ajouter une courbe représentant le délais entre la réception des doses et la vaccination

### ISSUE THREAD

**Issue by samber** [rozierguillaume/vaccintracker#2]
Merci pour ton travail @rozierguillaume !

![image](https://user-images.githubusercontent.com/2951285/106018738-296f1600-60c2-11eb-8a0a-e00724bfdf11.png)

Si tu es ok et que je ne quitte pas le boulot trop tard ce soir, je te le code dans la foulée ;)

**Comment by rozierguillaume** [comment]
Bonjour,
Merci beaucoup pour la proposition. Pour info le dépôt de code du site est ici : https://github.com/rozierguillaume/covidtracker-tools

Cette courbe est très intéressante. Mais pour info, à partir de ce soir on n'aura temporairement plus le nb de doses injectées, mais uniquement le nb de personnes vaccinées. Ça devrait être de nouveau le cas d'ici une à deux semaines, je te propose donc de développer cette feature à ce moment là !

**Comment by samber** [comment]
Ooookay

Dans ce cas, n'hésite pas à me ping quand ce sera bon ;)
