### ISSUE TITLE
Le diagramme première dose injectée n'est pas bon

### ISSUE THREAD

**Issue by HugoLd** [rozierguillaume/vaccintracker#4]
![image](https://user-images.githubusercontent.com/26521848/108558696-9315c500-72fa-11eb-903a-a983f73933fc.png)
Si je compare les premières doses injectées elles semblent enfaite correspondre aux total injectées
![image](https://user-images.githubusercontent.com/26521848/108558758-b17bc080-72fa-11eb-87d3-3cc581d932af.png)

**Comment by Dufgui** [comment]
le point du trait noir correspond a la courbe bleue foncée et bleue claire: donc le point correspond a premier doses injectées + secondes doses injectées donc 2.5 + 1 donc 3.5 donc pour moi on peut clore ce ticket @rozierguillaume

**Comment by BrunoSpy** [comment]
C'est en effet un graphique empilé : la courbe bleu clair s'ajoute à la courbe bleu foncé.
