### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by piotr-yuxuan** [rozierguillaume/vaccintracker#8]
Hello,

You are most probably already aware of that, but just to give you one more feedback: when loading https://covidtracker.fr/vaccintracker I get these errors.

![Screenshot 2021-03-12 at 18 33 40](https://user-images.githubusercontent.com/3686502/110983342-89afd380-8361-11eb-873a-3e4da8d0c236.png)

Anyway, I immensely thank you for what you do, and what you've done.

**Comment by machour** [comment]
Seems to be fixed now

**Comment by BrunoSpy** [comment]
Yes indeed, the fault was from a faulty CDN used by Github.
